version: '3'
volumes:
  data:
services:
    db:
      image: mariadb
      environment:
        MYSQL_ROOT_PASSWORD: 123456
        MYSQL_DATABASE: localhost
        MYSQL_USER: root
        MYSQL_PASSWORD: 123456
      volumes:
        - data:/var/lib/mysql
      ports:
        - "3307:3307"